### ISSUE TITLE
Problem with Istio step: I/O Timeout

### ISSUE THREAD

**Issue by k0105** [IBM/Microservices-deployment-with-PaaS-Containers-and-Serverless-Platforms#16]
Hi,

thank you for this great comparison. I have been able to execute all approaches except for Istio.
Running `kubectl api-versions | grep rbac` has returned `rbac.authorization.k8s.io/v1alpha1`, so I now try to execute `kubectl apply -f install/kubernetes/istio-rbac-alpha.yaml` which, however, prints `Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout`. Interestingly, this seems to have frozen my cluser, since now other commands yield the same error, e.g. when I run `kubectl create -f secret.yaml` or `kubectl api-versions | grep rbac` which worked before.

I have tried to reboot my "Worker Nodes" in Bluemix, but to no avail. And it seems I can't reboot the entire cluster, I could only delete it. Finally, stays on status "Pending" even though it clearly worked for the Kubernetes and OpenWhisk demos. Could you help me with debugging this?

Thank you in advance.

Best wishes,
k0105

**Comment by AnthonyAmanse** [comment]
It looks like your `kubectl` config changed to a minikube context. Try downloading the configuration file again.
```bash
$ bx cs cluster-config <your-cluster-name>
export KUBECONFIG=/Users/ibm/.bluemix/plugins/cs-cli/...
```  
Then run the export command

Alternatively, you can just do `$(bx cs cluster-config <your-cluster-name> | grep export)`. That should download the config then export KUBECONFIG in one line

You would need to do that every time you open/use a new terminal window.

**Comment by k0105** [comment]
I'm a little surprised, because I exported in a similar fashion, but your diagnosis is absolutely correct and worked perfectly. Thank you so much - this issue is solves.
